# Site settings
name: JQD
email: 894972206@qq.com
author: JQD
url: http://www.jiangquda.top
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/jiangquda
baseurl: "/JQD.github.io"
description: Actually, less is more!
meta_description: bug总比办法多
motto: It's our wits that make us men.
banner: ???

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

